apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.elasticsearch.statefulset.name }}
  namespace: {{ .Values.efk.namespace }}
spec:
  serviceName: {{ .Values.elasticsearch.service.name }}
  replicas: {{ .Values.elasticsearch.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.elasticsearch.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.elasticsearch.label }}
    spec:
      containers:
      - name: {{ .Values.elasticsearch.container.name }}
        image: {{ .Values.elasticsearch.container.image }}
        ports:
        {{- range .Values.elasticsearch.container.ports }}
        - containerPort: {{ .containerPort }}
          name: {{ .name }}
          protocol: {{ .protocol }}
        {{- end }}
        volumeMounts:
        - name: {{ .Values.elasticsearch.container.volumeMounts.name }}
          mountPath: {{ .Values.elasticsearch.container.volumeMounts.mountPath }}
        env:
          {{- range .Values.elasticsearch.container.env }}
          {{- if eq .name "node.name" }}
          - name: {{ .name }}
            valueFrom:
              fieldRef:
                fieldPath: {{ .value }}
          {{- else }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
          {{- end }}
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      # initContainers:
      # {{- range .Values.elasticsearch.initContainers }}
      # - name: {{ .name }}
      #   image: busybox
      #   command: {{ .command }}
      #   securityContext:
      #     privileged: true
      # {{- if eq .name "fix-permissions" }}
      #   volumeMounts:
      #   - name: data
      #     mountPath: /usr/share/elasticsearch/data
      # {{- end }}
      # {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.elasticsearch.volumeClaimTemplates.name }}
      labels:
        app: {{ .Values.elasticsearch.label }}
    spec:
      accessModes: {{ .Values.elasticsearch.volumeClaimTemplates.accessModes }}
      resources:
        requests:
          storage: {{ .Values.elasticsearch.volumeClaimTemplates.storage }}
