---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{.Values.fluentd.clusterrole.name: null}: null}
    namespace: {{.Values.efk.namespace: null}: null}
rules:
    - apiGroups:
          - ''
      resources:
          - pods
          - namespaces
      verbs:
          - get
          - list
          - watch
