---
apiVersion: v1
kind: Service
metadata:
    name: {{.Values.kibana.service.name: null}: null}
    namespace: {{.Values.efk.namespace: null}: null}
    labels:
        app: {{.Values.kibana.label: null}: null}
spec:
    selector:
        app: {{.Values.kibana.label: null}: null}
    type: {{.Values.kibana.service.type: null}: null}
    ports:
        - port: {{.Values.kibana.service.port: null}: null}
          targetPort: {{.Values.kibana.service.targetPort: null}: null}
          nodePort: {{.Values.kibana.service.nodePort: null}: null}
