apiVersion: v1
kind: Service
metadata:
  name: { { .Values.kibana.service.name } }
  namespace: { { .Values.efk.namespace } }
  labels:
    app: { { .Values.kibana.label } }
spec:
  selector:
    app: { { .Values.kibana.label } }
  type: { { .Values.kibana.service.type } }
  ports:
    - port: { { .Values.kibana.service.port } }
      targetPort: { { .Values.kibana.service.targetPort } }
      nodePort: { { .Values.kibana.service.nodePort } }
