apiVersion: apps/v1
kind: Deployment
metadata:
  name: rides-rec-dpl
  labels:
    app: rides-rec
spec:
  selector:
    matchLabels:
      app: rides-rec
  replicas: 3
  template:
    metadata:
      labels:
        app: rides-rec
    spec:
      containers:
      - name: rides-rec
        image: rides-rec:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: rides-rec-svc
  labels:
    app: rides-rec
spec:
  selector:
    app: rides-rec
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rides-rec-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: rides-rec.tn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rides-rec-svc
                port:
                  number: 5000