---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: fluentd-sa
    namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: fluentd-cr
    namespace: logging
rules:
    - apiGroups:
          - ''
      resources:
          - pods
          - namespaces
      verbs:
          - get
          - list
          - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: fluentd-crb
roleRef:
    kind: ClusterRole
    name: fluentd-cr
    apiGroup: rbac.authorization.k8s.io
subjects:
    - kind: ServiceAccount
      name: fluentd-sa
      namespace: logging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: fluentd-ds
    namespace: logging
    labels:
        app: fluentd
spec:
    selector:
        matchLabels:
            app: fluentd
    template:
        metadata:
            labels:
                app: fluentd
        spec:
            serviceAccount: fluentd-sa
            serviceAccountName: fluentd-sa
            tolerations:
                - key: node-role.kubernetes.io/master
                  effect: NoSchedule
            containers:
                - name: fluentd
                  image: >
                    fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch-amd64
                  env:
                      - name: FLUENT_ELASTICSEARCH_HOST
                        value: >
                          es-cluster-0.elasticsearch-svc.logging.svc.cluster.local
                      - name: FLUENT_ELASTICSEARCH_PORT
                        value: '9200'
                      - name: FLUENT_EALSTICSEARCH_SCHEME
                        value: http
                      - name: FLUENT_UID
                        value: '0'
                      - name: FLUENTD_SYSTEMD_CONF
                        value: disable
                  volumeMounts:
                      - name: varlog
                        mountPath: /var/log
                      - name: dockercontainers
                        mountPath: /var/lib/docker/containers
                        readOnly: true
            terminationGracePeriodSeconds: 30
            volumes:
                - name: varlog
                  hostPath:
                      path: /var/log
                - name: dockercontainers
                  hostPath:
                      path: /var/lib/docker/containers
