apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-dpl
  namespace: logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.5.0
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://es-cluster-0.elasticsearch-svc.logging.svc.cluster.local:9200"
          ports:
            - containerPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: logging
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
    - port: 8080
      targetPort: 5601
      nodePort: 30000

